services:
  service_test:
    build:
      context: ./service/
      dockerfile: Dockerfile.test
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        HOST_USERNAME: ${HOST_USERNAME:-user}
        HOST_GROUPNAME: ${HOST_GROUPNAME:-group}
    environment:
      - JUPYTER_PLATFORM_DIRS=1
      - COVERAGE_FILE=/tmp/.coverage
    ports:
      - 8888:8888
    user: "0:0"
    tty: false
    restart: no
    image: local/service-test:ci
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./service/app:/app
      - ./service/workspace:/workspace
      - ./service/data:/data
      - ./service/root/jupyter:/root/.jupyter
      - ./reports:/reports
    command: >
        install -d -m 0777 /reports/ci /tmp/pytest-cache &&
        pytest -q --maxfail=1 --disable-warnings
        --cov=/app/app
        --cov-report=xml:/reports/ci/coverage.xml
        -o cache_dir=/tmp/pytest-cache
